language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
  - openjdk7
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura  # Coberturaにする場合は以下を有効にする
  #- mvn clean test jacoco:report coveralls:jacoco  # Jacocoにする場合は以下を有効にする
